# Generated by Django 5.2 on 2025-04-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата верификации'),
        ),
    ]
