# Generated by Django 5.2 on 2025-04-16 17:05

import app_user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_siteuser_verified_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='siteuser',
            managers=[
                ('objects', app_user.models.CustomUserManager()),
            ],
        ),
    ]
